version: "3.9"

services:
  tg_video_downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg_video_downloader
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /path/to/your/downloads:/data/downloads
      - /path/to/your/app:/app
